spring:
  application:
    name: codingtest
  flyway:
    baseline-version: 1
    locations: classpath:db/migration,classpath:db/mock-data
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/codingtestdb
    username: testuser
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false