/*
 * This file is generated by jOOQ.
 */
package com.example.codingtest.domain.tables.records;


import com.example.codingtest.domain.tables.Book;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookRecord extends TableRecordImpl<BookRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.book.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.book.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.book.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.book.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.book.publish</code>.
     */
    public void setPublish(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.book.publish</code>.
     */
    public String getPublish() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.book.updated</code>.
     */
    public void setUpdated(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.book.updated</code>.
     */
    public String getUpdated() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.book.created</code>.
     */
    public void setCreated(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.book.created</code>.
     */
    public String getCreated() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, String title, Integer price, String publish, String updated, String created) {
        super(Book.BOOK);

        setId(id);
        setTitle(title);
        setPrice(price);
        setPublish(publish);
        setUpdated(updated);
        setCreated(created);
        resetChangedOnNotNull();
    }
}
