/*
 * This file is generated by jOOQ.
 */
package com.example.codingtest.domain.jooq.tables;


import com.example.codingtest.domain.jooq.Public;
import com.example.codingtest.domain.jooq.tables.records.AuthorBooksRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthorBooks extends TableImpl<AuthorBooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.author_books</code>
     */
    public static final AuthorBooks AUTHOR_BOOKS = new AuthorBooks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorBooksRecord> getRecordType() {
        return AuthorBooksRecord.class;
    }

    /**
     * The column <code>public.author_books.author_id</code>.
     */
    public final TableField<AuthorBooksRecord, Integer> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.author_books.book_id</code>.
     */
    public final TableField<AuthorBooksRecord, Integer> BOOK_ID = createField(DSL.name("book_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private AuthorBooks(Name alias, Table<AuthorBooksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthorBooks(Name alias, Table<AuthorBooksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.author_books</code> table reference
     */
    public AuthorBooks(String alias) {
        this(DSL.name(alias), AUTHOR_BOOKS);
    }

    /**
     * Create an aliased <code>public.author_books</code> table reference
     */
    public AuthorBooks(Name alias) {
        this(alias, AUTHOR_BOOKS);
    }

    /**
     * Create a <code>public.author_books</code> table reference
     */
    public AuthorBooks() {
        this(DSL.name("author_books"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public AuthorBooks as(String alias) {
        return new AuthorBooks(DSL.name(alias), this);
    }

    @Override
    public AuthorBooks as(Name alias) {
        return new AuthorBooks(alias, this);
    }

    @Override
    public AuthorBooks as(Table<?> alias) {
        return new AuthorBooks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorBooks rename(String name) {
        return new AuthorBooks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorBooks rename(Name name) {
        return new AuthorBooks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthorBooks rename(Table<?> name) {
        return new AuthorBooks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBooks where(Condition condition) {
        return new AuthorBooks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBooks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBooks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBooks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBooks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBooks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBooks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthorBooks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBooks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthorBooks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
