/*
 * This file is generated by jOOQ.
 */
package com.example.codingtest.domain;


import com.example.codingtest.domain.tables.Author;
import com.example.codingtest.domain.tables.AuthorBooks;
import com.example.codingtest.domain.tables.Book;
import com.example.codingtest.domain.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.author_books</code>.
     */
    public static final AuthorBooks AUTHOR_BOOKS = AuthorBooks.AUTHOR_BOOKS;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
